### ISSUE TITLE
Temperature in Deg C not displaying 0.5 deg increments.

### ISSUE THREAD

**Issue by Abnormal-User** [digitaldan/jomnilink#25]
Temperature output only displays the integer value. Any decimal value is not passed through resulting in a temperature which is reported as 26.5 dec C by the omni controller being displayed as 26.0 deg by the omnilink binding.

**Comment by digitaldan** [comment]
is this for the openHAB binding?  This repo is for a java library.  If so, you probably want to open a ticket up at https://github.com/openhab/openhab2-addons/issues  .  The binding does use this library, but those developers may not be watching for issues here.

**Comment by mjcumming** [comment]
Hi Dan, we were asked to open the issue here - I believe its your library that is returning temperature values as an integer when converting the omnilink temperature values to either C or F.

Mike

**Comment by digitaldan** [comment]
@boc-tothefuture and others, I just fixed temperature conversion in the library, i'm not sure what i was doing when i wrote it (hastily) , but it was not right.  The Utils class now returns floats instead of int for the F and C values, which adheres to the Omnilink API docs (see APPENDIX C - OMNI TEMPERATURE FORMAT)  , this may need some tweaking on your part to use in the binding.  I currently don't run a HAI system, so i have not tested.  Please use version 1.2.4 which is the latest, should be published to maven central in just a few.

**Comment by boc-tothefuture** [comment]
@digitaldan Thanks for tackling this..  I had them open it here - but I had planned to take a stab at it when I got some time but you beat me to it!  👍

**Comment by mjcumming** [comment]
@digitaldan Thank you.
