### ISSUE TITLE
Status classes are not immutable

### ISSUE THREAD

**Issue by boc-tothefuture** [digitaldan/jomnilink#8]
This leads to difficult reasoning in multhreaded environments.

**Comment by boc-tothefuture** [comment]
Style question for you @digitaldan 
  We have a lot of status classes that are mostly value type objects that we are considering making immutable w/ a lot of repetition in the code base.
  
  Are you opposed to using lombok to abstract that away into annotations?  I can take a cut a PR and we can see.  But if you have philosophical objections to lombok its not worth the PR.

**Comment by digitaldan** [comment]
>We have a lot of status classes that are mostly value type objects that we are considering making immutable w/ a lot of repetition in the code base.

We do, as you can probably see from the toString methods (which don't make a lot of sense) I had eclipse generate a lot of boiler plate code for me, this was in 2008, so a long time ago.

>Are you opposed to using lombok to abstract that away into annotations?

Not at all, I have to admit its been a few years since that project has crossed my radar.  While I would like to keep this project as thin as possible from a dependencies POV, I think lombok could be very useful. Feel free to submit a PR.

Sorry about the late response, I loose github messages often in my firehose stream of OH and ESH notifications.   If I don't respond, bump my name a few times!

**Comment by digitaldan** [comment]
> While I would like to keep this project as thin as possible

And since lombok is only compile time dependency, thats even better :-)

**Comment by digitaldan** [comment]
Can we close this?

**Comment by boc-tothefuture** [comment]
Yep.  Although I have not had the time to test it in OpenHAB yet.

**Comment by digitaldan** [comment]
I have been running since we merged, lgtm
